server:
  port: 9999

spring:
  datasource:
    username: root
    password: q451234@
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.sensor: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.sensor.*.entity

